#%RAML 1.0 Extension

extends: https://raw.githubusercontent.com/VEuPathDB/docs-api-schema/v2.0.1/libraries/base-service.raml

title: Organism Specific ID Service
version: v1.0.0
mediaType: application/json

uses:
  error: https://raw.githubusercontent.com/VEuPathDB/docs-api-schema/v2.0.1/libraries/errors.raml
  lib: schema/library.raml

securitySchemes:
  basic:
    description: HTTP Basic Authentication
    type: Basic Authentication

securedBy: basic

/organisms:
  get:
    queryParameters:
      organismName:
        type: string
        required: false
  post:
    body:
      type: object
      properties:
        organismName:
        geneTemplate:
        startingGeneInt:
          type: integer
          format: int64
          minimum: 1
          maximum: 9223372036854775807
        startingTranscriptInt:
          type: integer
          format: int64
          minimum: 1
          maximum: 9223372036854775807
    responses:
      200:
        body:
          type: string
      400:
        body:
          type: error.BadRequestError
      401:
        body:
          type: error.UnauthorizedError
      403:
        body:
          type: error.ForbiddenError
      422:
        body:
          type: error.UnprocessableEntityError
      500:
        body:
          type: error.ServerError
  /{organism-id}:
    uriParameters:
      organism-id:
        type: string
        required: true
    get:
    put:

/geneSets:
  get:
    queryParameters:
      appName:
        type: string
      startTimeStamp:
        type: integer
        format: int64
        minimum: 0
        maximum: 9223372036854775807
      endTimeStamp:
        type: integer
        format: int64
        minimum: 0
        maximum: 9223372036854775807
  post:
  /{gene-set-id}:
    uriParameters:
      gene-set-id:
        type: string
        required: true
    get:
