#%RAML 1.0 Extension

extends: https://raw.githubusercontent.com/VEuPathDB/docs-api-schema/v2.0.1/libraries/base-service.raml

title: Organism Specific ID Service
version: v1.0.0
mediaType: application/json

uses:
  error: https://raw.githubusercontent.com/VEuPathDB/docs-api-schema/v2.0.1/libraries/errors.raml
#  lib: schema/library.raml

securitySchemes:
  basic:
    description: HTTP Basic Authentication
    type: Basic Authentication

securedBy: basic

/organisms:
  displayName: Organisms
  get:
    displayName: Get Organisms
    description: |
      Returns an array of the organisms currently registered with the OSID
      service.

      The results may be optionally filtered to a single result by use of the
      `organismName` query parameter.
    queryParameters:
      organismName?:
        type: string
        description: |
          Name of the organism to look up.
          This field supports wildcards using the asterisk (`*`) character.
      createdAfter?:
        type: ZeroBasedLong
        description: |
          Unix timestamp of the earliest records this query should match.
          No records created before this timestamp will be returned.
      createdBefore?:
        type: ZeroBasedLong
        description: |
          Unix timestamp of the latest records this query should match.
          No records created after this timestamp will be returned.
      createdBy?:
        type: string
        description: |
          Filter results on the ID or name of the user that created the records.
    responses:
      200:
        body:
          type: OrganismResponse[]
          example:
            - organismId: 24
              organismName: Plasmodium falciparum 3D7
              template: "PF3D7_%07d"
              geneIntStart: 1500000
              geneIntCurrent: 1501203
              transcriptIntStart: 1
              transcriptIntCurrent: 57
              createdOn: 2020-08-25T11:43:16Z
              createdBy: 26

      401:
        body: error.UnauthorizedError
      403:
        body: error.ForbiddenError
      422:
        body: error.UnprocessableEntityError
      500:
        body: error.ServerError
  post:
    description: |
      Registers a new organism with the OSID service, returning the ID of the
      newly registered organism record on success.
    body:
      type: OrganismPostRequest
    responses:
      200:
        body:
          description: Primary key value for the newly created organism record.
          type: OneBasedLong
      400:
        body: error.BadRequestError
      401:
        body: error.UnauthorizedError
      403:
        body: error.ForbiddenError
      422:
        body: error.UnprocessableEntityError
      500:
        body: error.ServerError
  /{organism-id}:
    uriParameters:
      organism-id:
        description: |
          May be either the primary key value for the specific organism or the
          organism name.
        type: string
    get:
      description: |
        Looks up and returns the details of a single organism record by record
        id.
      responses:
        200:
          body: OrganismResponse
        401:
          body: error.UnauthorizedError
        404:
          body: error.NotFoundError
        500:
          body: error.ServerError
    put:
      description: |
        Updates a specific organism record by replacing specific fields with the
        new values in the request body.

        Put requests will be rejected if they violate the following rules:

        1. The new `startingInt` value must not be lower than the organism
           record's `currentInt` value.
        2. The `template` value must not be null or empty.
        3. The `template` value must contain a single printf integer
           placeholder.  (See [the Java string formatting cheatsheet](https://dzone.com/articles/how-to-format-a-string-clarified))
        4. The `organismName` value must not be null or empty.
      body: OrganismPutRequest
      responses:
        204:
        400:
          body: error.BadRequestError
        401:
          body: error.UnauthorizedError
        403:
          body: error.ForbiddenError
        404:
          body: error.NotFoundError
        422:
          body: error.UnprocessableEntityError
        500:
          body: error.ServerError

/idSetCollections:
  get:
    queryParameters:
      createdAfter?:
        type: ZeroBasedLong
        description: |
         Unix timestamp.

         Filter results to records created after this date.
      createdBefore?:
        type: ZeroBasedLong
        description: |
          Unix timestamp.

          Filter results to records created before this date.
      createdBy?:
        type: string
        description: |
          Filter results by the user who created the records.  The value may be
          either a user name or user id value.
      name?:
        type: string
        description: |
          Filter results by name.  This field supports wildcards using the
          asterisk (`*`) character.
    responses:
      200:
        body: CollectionResponse[]
      401:
        body: error.UnauthorizedError
      403:
        body: error.ForbiddenError
      500:
        body: error.ServerError
  post:
    body: IdSetCollectionPostRequest
    responses:
      200:
        body: CollectionResponse
      400:
        body: error.BadRequestError
      401:
        body: error.UnauthorizedError
      403:
        body: error.ForbiddenError
      422:
        body: error.UnprocessableEntityError
      500:
        body: error.ServerError

  /{collection-id}:
    uriParameters:
      collection-id: OneBasedLong
    get:
      responses:
        200:
          body: CollectionResponse
        401:
          body: error.UnauthorizedError
        404:
          body: error.NotFoundError
        500:
          body: error.ServerError

/idSets:
  get:
    queryParameters:
      createdAfter?: ZeroBasedLong
      createdBefore?: ZeroBasedLong
      createdBy?:
    responses:
      200:
        body:
          type: IdSetResponse[]
          example:
            - idSetId: 48
              collectionId: 12
              organismId: 1
              template: PF3D7_%07d
              geneIntStart: 150000
              generatedGeneCount: 2
              generatedIds:
                - geneId: PF3D7_0145842
                  transcripts:
                    - PF3D7_0145842.R57
                    - PF3D7_0145842.R58
                    - PF3D7_0145842.R59
                    - PF3D7_0145842.R78
                  proteins:
                    - PF3D7_0145842.P57
                    - PF3D7_0145842.P58
                    - PF3D7_0145842.P59
                    - PF3D7_0145842.P78
                - geneId: PF3D7_150001
                  transcripts: []
                  proteins: []
                - geneId: PF3D7_150002
                  transcripts:
                    - PF3D7_150002.R79
                  proteins:
                    - PF3D7_150002.P79
              createdOn: 2020-08-25T11:43:16Z
              createdBy: 215

      401:
        body: error.UnauthorizedError
      403:
        body: error.ForbiddenError
      500:
        body: error.ServerError
  post:
    body: IdSetPostRequest
    responses:
      200:
        body:
          type: IdSetResponse
          example:
            idSetId: 48
            collectionId: 12
            organismId: 1
            template: PF3D7_%07d
            geneIntStart: 150000
            generatedGeneCount: 2
            generatedIds:
              - geneId: PF3D7_150001
                transcripts: []
                proteins: []
              - geneId: PF3D7_150002
                transcripts: []
                proteins: []
            createdOn: 2020-08-25T11:43:16Z
            createdBy: 123
      400:
        body: error.BadRequestError
      401:
        body: error.UnauthorizedError
      403:
        body: error.ForbiddenError
      422:
        body: error.UnprocessableEntityError
      500:
        body: error.ServerError
  /{id-set-id}:
    uriParameters:
      id-set-id: OneBasedLong
    get:
      responses:
        200:
          body:
            type: IdSetResponse
            example:
              idSetId: 48
              collectionId: 12
              organismId: 1
              template: PF3D7_%07d
              geneIntStart: 150000
              generatedGeneCount: 2
              generatedIds:
              - geneId: PF3D7_0145842
                transcripts:
                - PF3D7_0145842.R57
                - PF3D7_0145842.R58
                - PF3D7_0145842.R59
                - PF3D7_0145842.R78
                proteins:
                - PF3D7_0145842.P57
                - PF3D7_0145842.P58
                - PF3D7_0145842.P59
                - PF3D7_0145842.P78
              - geneId: PF3D7_150001
                transcripts: []
                proteins: []
              - geneId: PF3D7_150002
                transcripts:
                - PF3D7_150002.R79
                proteins:
                - PF3D7_150002.P79
              createdOn: 2020-08-25T11:43:16Z
              createdBy: 546
        401:
          body: error.UnauthorizedError
        403:
          body: error.ForbiddenError
        404:
          body: error.NotFoundError
        500:
          body: error.ServerError
    patch:
      body:
        type: IdSetPatchEntry[]
        example:
          - geneId: PF3D7_0145842
            transcripts: 4
          - geneId: PF3D7_0120354
            transcripts: 18
      responses:
        200:
          body: IdSetResponse
        400:
          body: error.BadRequestError
        401:
          body: error.UnauthorizedError
        403:
          body: error.ForbiddenError
        404:
          body: error.NotFoundError
        500:
          body: error.ServerError

/auth:
  displayName: User Management
  post:
    displayName: Create User
    description: |
      Register a new user/application and issue an API key for that user to
      access this service.

      This endpoint may only be used by a user or application with access to the
      admin credentials.
    body:
      type: UserPostRequest
      example:
        username: someApplicationName
    responses:
      200:
        body: NewUserResponse
      400:
        body: error.BadRequestError
      401:
        body: error.UnauthorizedError
      403:
        body: error.ForbiddenError
      422:
        body: error.UnprocessableEntityError
      500:
        body: error.ServerError
  /{user-identifier}:
    uriParameters:
      user-identifier:
        type: string
        description: |
          Either the primary key id or the exact username of the user to lookup.
    get:
      displayName: Lookup User
      description: |
        Look up a user by name or ID.

        This endpoint may only be used by a user or application with access to
        the admin credentials.
      responses:
        200:
          body: NewUserResponse
        401:
          body: error.UnauthorizedError
        500:
          body: error.ServerError

types:
  TemplatePattern:
    displayName: Gene ID Template String
    description: |
      Gene ID template string.  Must include at least 1 integer format parameter
      for injecting the id counter value into the template.

      The template string will be expanded using Java's String.format method
      which will expect a Java format parameter.

      See [the Java string formatting cheatsheet](https://dzone.com/articles/how-to-format-a-string-clarified)
      for possible parameters and modifiers.

      The example parameter for this field is `%07d` which breaks down to:

      * `%` = parameter start marker
      * `07` = left pad the number with zeros for a total length of 7 digits
      * `d` = format as an int

      **NOTE**: When used, this template string will be passed exactly int64
      value and nothing else.  Templates should only include `%d` based formats.
      If the template needs more than one instance of the counter int64 value,
      positional parameters may be used.
    type: string
    pattern: "^.*%[0-9,+\\- $.]*d.*$"
    minLength: 5
    example: PF3D7_%07d

  ZeroBasedInt:
    description: Int32 value with a valid value range of `[0..2147483647]`.
    type: integer
    format: int32
    minimum: 0
    maximum: 2147483647

  ZeroBasedLong:
    description: |
      Int64 value with a valid value range of `[0..9223372036854775807]`.
    type: integer
    format: int64
    minimum: 0
    maximum: 9223372036854775807

  OneBasedLong:
    description: |
      Int64 value with a valid value range of `[1..9223372036854775807]`.
    type: integer
    format: int64
    minimum: 1
    maximum: 9223372036854775807

  IdSetPostRequest:
    type: object
    properties:
      collectionId:
        type: OneBasedLong
      organismId:
        description: |
          Internal storage primary key for an organism registered with the OSID
          service.
        type: OneBasedLong
      generateGenes:
        description: |
          Number of gene IDs generated by the OSID service for the current
          organism.
        type: ZeroBasedInt
    additionalProperties: false

  IdSetResponse:
    type: object
    properties:
      idSetId:
        description: |
          Internal storage primary key for an ID set.  Used to make requests
          that operate on or retrieve one specific ID set.
        type: OneBasedLong
      collectionId: OneBasedLong
      organismId: OneBasedLong
      template: TemplatePattern
      geneIntStart: OneBasedLong
      generatedGeneCount: ZeroBasedInt
      generatedIds: GeneratedTranscriptEntry[]
      createdOn: datetime
      createdBy: OneBasedLong
    additionalProperties: false

  GeneratedTranscriptEntry:
    type: object
    properties:
      geneId:
        type: string
        minLength: 3
      transcripts: string[]
      proteins: string[]
    additionalProperties: false
    example:
      geneId: PF3D7_0145842
      transcripts:
        - PF3D7_0145842.R57
        - PF3D7_0145842.R58
        - PF3D7_0145842.R59
        - PF3D7_0145842.R78
      proteins:
        - PF3D7_0145842.P57
        - PF3D7_0145842.P58
        - PF3D7_0145842.P59
        - PF3D7_0145842.P78
  IdSetPatchEntry:
    type: object
    properties:
      geneId:
        type: string
        minLength: 3
      transcripts: ZeroBasedInt
    additionalProperties: false
    example:
      geneId: PF3D7_0145842
      transcripts: 4

  OrganismPostRequest:
    displayName: Organism Record Create/Update Request Body
    type: object
    properties:
      organismName:
        type: string
        minLength: 3
      template: TemplatePattern
      geneIntStart:
        description: Starting point for the gene ID integer counter.
        type: OneBasedLong
      transcriptIntStart:
        description: Starting point for the transcript ID integer counter.
        type: OneBasedLong
    additionalProperties: false
    example:
      organismName: Plasmodium falciparum 3D7
      template: "PF3D7_%07d"
      geneIntStart: 1500000
      transcriptIntStart: 1

  OrganismPutRequest:
    displayName: Organism Record Create/Update Request Body
    type: object
    properties:
      template: TemplatePattern
      geneIntStart?:
        description: |
          Starting point for the gene ID integer counter.

          **NOTE** This field may only be changed if no gene ids have yet been
          issued for this organism.
        type: OneBasedLong
      transcriptIntStart?:
        description: |
          Starting point for the transcript ID integer counter.

          **NOTE** This field may only be changed if no transcript ids have yet
          been issued for this organism.
        type: OneBasedLong
    additionalProperties: false
    example:
      template: "PF3D7_%07d"
      geneIntStart: 1500000
      transcriptIntStart: 1

  OrganismResponse:
    type: object
    properties:
      organismId:
        description: |
          Internal primary key value assigned to this organism record.
        type: OneBasedLong
      organismName:
        type: string
        minLength: 3
      template:
        description: Currently assigned gene ID template string.
        type: TemplatePattern
      geneIntStart:
        description: Starting point for the gene ID integer counter.
        type: OneBasedLong
      transcriptIntStart:
        description: Starting point for the transcript ID integer counter.
        type: OneBasedLong
      geneIntCurrent:
        description: Current value for the gene ID integer counter.
        type: OneBasedLong
      transcriptIntCurrent:
        description: Current value for the transcript ID integer counter.
        type: OneBasedLong
      createdOn:
        description: Timestamp of when this record was created.
        type: datetime
      createdBy:
        description: User ID of the user/app that created this record.
        type: OneBasedLong
    additionalProperties: false
    example:
      organismId: 24
      organismName: Plasmodium falciparum 3D7
      template: "PF3D7_%07d"
      geneIntStart: 1500000
      geneIntCurrent: 1501203
      transcriptIntStart: 1
      transcriptIntCurrent: 57
      createdOn: 2020-08-25T11:43:16Z
      createdBy: 26

  NewUserResponse:
    type: object
    properties:
      userId: OneBasedLong
      username:
      apiKey:
      issued: datetime
    additionalProperties: false
    example:
      userId: 123456
      username: "some user name"
      apiKey: "d831d10e47de4154912ea7a8f1c633c3"
      issued: "2020-05-25T13:18:26Z"

  CollectionResponse:
    type: object
    properties:
      collectionId: OneBasedLong
      name:
      createdBy: OneBasedLong
      createdOn: datetime
      idSets: IdSetResponse[]
    additionalProperties: false

  IdSetCollectionPostRequest:
    type: object
    properties:
      name:
    additionalProperties: false

  UserPostRequest:
    type: object
    properties:
      username:
        type: string
        minLength: 3
    additionalProperties: false
    example:
      username: "some user name"
