#%RAML 1.0 Extension

extends: https://raw.githubusercontent.com/VEuPathDB/docs-api-schema/v2.0.1/libraries/base-service.raml

title: Organism Specific ID Service
version: v1.0.0
mediaType: application/json

uses:
  error: https://raw.githubusercontent.com/VEuPathDB/docs-api-schema/v2.0.1/libraries/errors.raml
  lib: schema/library.raml

# TODO: THIS SHOULD BE HEADER
securitySchemes:
  basic:
    description: HTTP Basic Authentication
    type: Basic Authentication

securedBy: basic

/organisms:
  get:
    queryParameters:
      organismName:
        type: string
        required: false
  post:
  /{organism-id}:
    get:
    put:

/geneSets:
  get:
    queryParameters:
      appName:
        type: string
      startTimeStamp:
        type: integer
        format: int64
      endTimeStamp:
        type: integer
        format: int64
  post:
  /{gene-set-id}:
    get:
