= Organism Specific ID Service
:toc: left
:source-highlighter: pygments
:icons: font
// Github specifics
ifdef::env-github[]
:tip-caption: :bulb:
:note-caption: :information_source:
:important-caption: :heavy_exclamation_mark:
:caution-caption: :fire:
:warning-caption: :warning:
endif::[]
// URLs and such
:vgit: https://github.com/VEuPathDB
:docs: https://veupathdb.github.io/service-osi-generator/api.html
Elizabeth Paige Harper <epharper@upenn.edu>
v1.0.0

== Additional Info

* link:{docs}[API Documentation]
* link:{vgit}/service-osi-generator/blob/master/deployment.adoc[Deployment Info]
* link:{vgit}/example-jaxrs-container-service[Starting Template]

== Development

=== Requirements

[cols="1,3"]
|===
h| Docker
 | for building/running service image
h| Docker Compose
 | for building/running service image
h| NodeJS
 | for doc generation
h| NPM
 | for doc generation
h| Java14+
 | service is using Java14
h| Maven
a| used to build non-published dependencies:

* link:{vgit}/FgpUtil[FgpUtil]
* link:https://github.com/mulesoft-labs/raml-for-jax-rs[raml-for-jax-rs]
|===

== Running the Service

Due to this service's dependence on a running postgres instance, having Docker and Docker Compose
available is more convenient, but it is not required.

For runtime requirements see link:{docs}[the API documentation].

=== With Docker Compose

[CAUTION]
--
It's strongly advised that the required environment variables be set in a file named `.env` in the
project root.  This will help avoid putting protected/credential information in your bash history.

Docker Compose will automatically read this file and use the environment variables set there when
starting up the service containers.

For more information see
link:https://docs.docker.com/compose/environment-variables/#the-env-file[the Docker Compose docs].
--

Spinning up the service containers with Docker Compose can be done with the following command:

[source, bash-shell]
----
$ docker-compose -f docker/docker-compose.dev.yml up
----

This will build and start both the service and database containers.

The services will be made available from your host machine at `localhost:5432` for postgres and
`localhost:8080` for the HTTP server.

== Docker

This project includes 2 Docker Compose configs as well as 2 Docker configs for the HTTP service.
One of each for production and development.  The postgres Docker config is used for both development
and production.

=== Production Docker

`docker/DB.Dockerfile`:: Postgres instance
`docker/docker-compose.prod.yml`:: Docker Compose configuration.
`docker/SVC.prod.Dockerfile`:: Docker configuration.

== Testing the Service

=== Unit Tests

Unit tests are run automatically as part of the build, but can be run locally using the command
`./gradlew test`.  All unit tests can be found under `./src/test/java/`.

=== API Tests

Running the API tests requires both Docker and Docker Compose.

The API tests can be run using the command `make api-test`.  This will spin up a temporary instance
of both the HTTP service and the Postgres instance then run the battery of tests against the running
instances.

The API tests are defined under the `./api-test` sub project.
