version: "3.5"

services:
  postgres:
    build:
      context: ..
      dockerfile: docker/DB.Dockerfile
    ports:
      - 5432:5432
    environment:
      # Admin user password
      POSTGRES_PASSWORD:

      # Service user password
      DB_PASSWORD:
  osi-service:
    build:
      context: ..
      dockerfile: docker/SVC.dev.Dockerfile
    ports:
      - 8080:8080
    depends_on:
      - postgres
    environment:
      # Postgres connection details
      #
      # DB_PASSWORD here must match DB_PASSWORD in the postgres environment
      # settings.
      DB_PASSWORD:
      #      DB_USERNAME: osi_service
      #      DB_PORT: 5432
      #      DB_POOL_SIZE: 20
      #      DB_HOST: postgres
      #      DB_NAME: postgres

      # User administration user credentials
      ADMIN_USER:
      ADMIN_PASS:
    command: >-
      sh -c "while ! nc -z postgres 5432; do
        echo 'waiting for postgres';
        sleep 1;
      done;
      java -jar /service.jar"
  test:
    build:
      context: ../api-test
      dockerfile: Dockerfile
    depends_on:
      - osi-service
    environment:
      ADMIN_USER:
      ADMIN_PASS:
      DB_PASSWORD:
      POSTGRES_PASSWORD:
