version: "3.5"

services:
  postgres:
    image: veupathdb/osi-generator-database
    volumes:
    - postgres_data:/var/lib/postgresql/data
    networks:
    - internal
    environment:
      # Admin user password
      POSTGRES_PASSWORD: ${DATABASE_ADMINPASSWD}

      # Service user password
      DB_PASSWORD: ${DATABASE_PASSWORD}
  service:
    image: veupathdb/osi-generator-service
    depends_on:
    - postgres
    environment:
      # Postgres connection details
      DB_PASSWORD: ${DATABASE_PASSWORD}
      DB_USERNAME: ${DATABASE_USER:-osi_service}
      DB_PORT: ${DATABASE_PORT:-5432}
      DB_POOL_SIZE: ${DATABASE_POOLSIZE:-20}
      DB_HOST: ${DATABASE_HOST:-postgres}
      DB_NAME: ${DATABASE_NAME:-postgres}

      # User administration user credentials
      ADMIN_USER: ${SERVICE_ADMIN}
      ADMIN_PASS: ${SERVICE_PASSWORD}

      SERVER_PORT: ${SERVICE_PORT:-80}
    command: >-
      sh -c "while ! nc -z ${DATABASE_HOST:-postgres} ${DATABASE_PORT:-5432}; do
        echo 'waiting for postgres';
        sleep 1;
      done;
      java -jar /service.jar"
    networks:
    - internal
    - traefik
    labels:
    - "traefik.http.routers.${TRAEFIK_ROUTER:-osid-service-dev}.rule=Host(`${TRAEFIK_ROUTER:-osid-service-dev.local.apidb.org}`)"
    - "traefik.http.routers.${TRAEFIK_ROUTER:-osid-service-dev}.tls=true"
    - "traefik.http.routers.${TRAEFIK_ROUTER:-osid-service-dev}.entrypoints=${TRAEFIK_ENTRYPOINTS:-local}"
    - "traefik.http.services.${TRAEFIK_ROUTER:-osid-service-dev}.loadbalancer.server.port=${SERVICE_PORT:-80}"
    - "traefik.docker.network=traefik"

networks:
  internal:
    internal: true
  traefik:
    external: true

volumes:
  postgres_data:
