version: "3.5"

services:
  postgres:
    image: veupathdb/osi-generator-database
    volumes:
    - postgres_data:/var/lib/postgresql/data
    networks:
    - internal
    environment:
      # Admin user password
      POSTGRES_PASSWORD: zOFK6OHgkpvWfhTvc2OtHPOVCxT47mGwI

      # Service user password
      DB_PASSWORD: zOFK6OHgkpvWfhTvc2OtHPOVCxT47mGwI
  service:
    image: veupathdb/osi-generator-service
    depends_on:
    - postgres
    environment:
      # Postgres connection details
      #
      # DB_PASSWORD here must match DB_PASSWORD in the postgres environment
      # settings.
      DB_PASSWORD: zOFK6OHgkpvWfhTvc2OtHPOVCxT47mGwI
      DB_USERNAME: osi_service
      DB_PORT: 5432
      DB_POOL_SIZE: 20
      DB_HOST: postgres
      DB_NAME: postgres

      # User administration user credentials
      ADMIN_USER: adminuser
      ADMIN_PASS: zOFK6OHgkpvWfhTvc2OtHPOVCxT47mGwI

      SERVER_PORT: 80
    command: >-
      sh -c "while ! nc -z postgres 5432; do
        echo 'waiting for postgres';
        sleep 1;
      done;
      java -jar /service.jar"
    networks:
    - internal
    - traefik
    labels:
    - "traefik.http.routers.osid-service-dev.rule=Host(`osid-service-dev.local.apidb.org`)"
    - "traefik.http.routers.osid-service-dev.tls=true"
    - "traefik.http.routers.osid-service-dev.entrypoints=local"
    - "traefik.http.services.osid-service-dev.loadbalancer.server.port=80"
    - "traefik.docker.network=traefik"


networks:
  internal:
    internal: true
  traefik:
    external: true

volumes:
  postgres_data:
