#%RAML 1.0 Library

uses:
  lib: ../library.raml

types:
  IdSetPostRequest:
    type: object
    properties:
      organismId: lib.OneBasedLong
      generateGenes: lib.ZeroBasedInt
  IdSetResponse:
    type: object
    properties:
      idSetId: lib.OneBasedLong
      template: lib.TemplatePattern
      geneIntStart: lib.OneBasedLong
      generatedGeneCount: lib.ZeroBasedInt
      generatedIds: GeneratedTranscriptEntry[]
  GeneratedTranscriptEntry:
    type: object
    properties:
      geneId:
        type: string
        minLength: 3
      transcripts: string[]
      proteins: string[]
  IdSetPatchEntry:
    type: object
    properties:
      geneId:
        type: string
        minLength: 3
      transcripts: lib.OneBasedInt
